### PR TITLE
cosmos endpoints

### PR DESCRIPTION
**Pull request by chalabi2**
- add validators endpoint
- remove target
- fix code deletions
- complete /validators
- add governance

Adds /validators & /proposals with sub queries within them

### CODE REVIEW

**Review by ChristianBorst — APPROVED** [review]
This looks good to me, in addition to using constants for DB keys I think it would be nice to have a loop that periodically runs the `get_cached_whatever()` functions when they're expired to refresh our caches.

**Comment by ChristianBorst** [comment]
I think you also need to rebase off of the current main, it looks like you have some strange commit history in the PR

**Comment by chalabi2** [comment]
Yeah /target wasn't in the .gitignore file so I mistakenly added it and then removed the file from that commit.

**Comment by chalabi2** [comment]
> This looks good to me, in addition to using constants for DB keys I think it would be nice to have a loop that periodically runs the `get_cached_whatever()` functions when they're expired to refresh our caches.

Ive added the cache refresh for the validators endpoint, please let me know how that looks and ill add it for the delegations and proposals as well.

**Comment by ChristianBorst** [comment]
@chalabi2 Sorry, didn't realize you were waiting on a re-review. That looks good to me, except I think the cache refresh should run at least as long as the cache timeout is. Right now you have the cache refresh loop running every 60 seconds but if everything is cached at 300 seconds you can slow that loop down.

**Pull request merged**
